start-kind:
	echo "Starting kind cluster"
	./start-kind-cluster.sh

stop-kind:
	echo "Starting kind cluster"
	./stop-kind-cluster.sh

dev:
	echo "Starting Skaffold using profile: dev"
	skaffold dev -n default --status-check=false --tail
