name: Release workflow
run-name: Running build and release workflow 🚀

on:
  release:
    types: [published]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: runtime
          platforms: linux/amd64
          push: true
          tags: helkaroui/spark-reverse-proxy:latest,helkaroui/spark-reverse-proxy:${{ github.event.release.tag_name }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: helkaroui/spark-reverse-proxy
