name: Test & Build workflow
run-name: Running test & build workflows 🚀

on:
  push:
    branches:
      - 'master'
      - 'releases/**'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: runtime
          platforms: linux/amd64
          push: true
          tags: helkaroui/spark-reverse-proxy:latest,helkaroui/spark-reverse-proxy:1.0.0
